[[couchbase.configuration]]
= Installation & Configuration

This chapter describes the common installation and configuration steps needed when working with the library.

[[installation]]
== Installation

All versions intended for production use are distributed across Maven Central and the Spring release repository.
As a result, the library can be included like any other maven dependency:

.Including the dependency through maven
====
[source,xml]
----
<dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-couchbase</artifactId>
    <version>4.0.0.RELEASE</version>
</dependency>
----
====

This will pull in several dependencies, including the underlying Couchbase Java SDK, common Spring dependencies and also Jackson as the JSON mapping infrastructure.

You can also grab snapshots from the https://repo.spring.io/libs-snapshot[spring snapshot repository] and milestone releases from the https://repo.spring.io/libs-milestone[milestone repository].
Here is an example on how to use the current SNAPSHOT dependency:

.Using a snapshot version
====
[source,xml]
----
<dependency>
  <groupId>org.springframework.data</groupId>
  <artifactId>spring-data-couchbase</artifactId>
  <version>4.0.0.BUILD-SNAPSHOT</version>
</dependency>

<repository>
  <id>spring-libs-snapshot</id>
  <name>Spring Snapshot Repository</name>
  <url>https://repo.spring.io/libs-snapshot</url>
</repository>
----
====

Once you have all needed dependencies on the classpath, you can start configuring it.
Only Java config is supported (XML config has been removed in 4.0).

[[configuration-java]]
== Annotation-based Configuration ("JavaConfig")

To get started, all you need to do is subclcass the `AbstractCouchbaseConfiguration` and implement the abstract methods.

.Extending the `AbstractCouchbaseConfiguration`
====
[source,java]
----

@Configuration
public class Config extends AbstractCouchbaseConfiguration {

    @Override
    public String getConnectionString() {
        return "couchbase://127.0.0.1";
    }

    @Override
    public String getUserName() {
        return "Administrator";
    }

    @Override
    public String getPassword() {
        return "password";
    }

    @Override
    public String getBucketName() {
        return "travel-sample";
    }
}
----
====

The connection string is made up of a list of hosts and an optional scheme (`couchbase://`) as shown in the code above.
All you need to provide is a list of Couchbase nodes to bootstrap into (separated by a `,`). Please note that while one
host is sufficient in development, it is recommended to add 3 to 5 bootstrap nodes here. Couchbase will pick up all nodes
from the cluster automatically, but it could be the case that the only node you've provided is experiencing issues while
you are starting the application.

The `userName` and `password` are configured in your Couchbase Server cluster through RBAC (role-based access control).
The `bucketName` reflects the bucket you want to use for this configuration.

Additionally, the SDK environment can be tuned by overriding the `configureEnvironment` method which takes a
`ClusterEnvironment.Builder` to return a configured `ClusterEnvironment`.

Many more things can be customized and overridden as custom beans from this configuration (for example repositories,
validation and custom converters).

TIP: If you use `SyncGateway` and `CouchbaseMobile`, you may run into problem with fields prefixed by `_`.
Since Spring Data Couchbase by default stores the type information as a `_class` attribute this can be problematic.
Override `typeKey()` (for example to return `MappingCouchbaseConverter.TYPEKEY_SYNCGATEWAY_COMPATIBLE`) to change the
name of said attribute.

If you start your application, you should see Couchbase INFO level logging in the logs, indicating that the underlying
Couchbase Java SDK is connecting to the database. If any errors are reported, make sure that the given credentials
and host information are correct.

