[[couchbase.template]]
= Template & direct operations

The template provides lower level access to the underlying database and also serves as the foundation for repositories.
Any time a repository is too high-level for you needs chances are good that the templates will serve you well. Note that
you can always drop into the SDK directly through the beans exposed on the `AbstractCouchbaseConfiguration`.

[[template.ops]]
== Supported operations

The template can be accessed through the `couchbaseTemplate`  and `reactiveCouchbaseTemplate` beans out of your context.
Once you've got a reference to it, you can run all kinds of operations against it.
Other than through a repository, in a template you need to always specify the target entity type which you want to get converted.

The templates use a fluent-style API which allows you to chain in optional operators as needed. As an example, here is
how you store a user and then find it again by its ID:

.Fluent template access
====
[source,java]
----
// Create an Entity
User user = new User(UUID.randomUUID().toString(), "firstname", "lastname");

// Upsert it
couchbaseTemplate.upsertById(User.class).one(user);

// Retrieve it again
User found = couchbaseTemplate.findById(User.class).one(user.getId());
----
====

If you wanted to use a custom (by default durability options from the `@Document` annotation will be used) durability requirement for the `upsert` operation you can chain it in:

.Upsert with durability
====
[source,java]
----
User modified = couchbaseTemplate
  .upsertById(User.class)
  .withDurability(DurabilityLevel.MAJORITY)
  .one(user);
----
====

In a similar fashion, you can perform a N1QL operation:

.N1QL query on the template
====
[source,java]
----
final List<User> foundUsers = couchbaseTemplate
  .findByQuery(User.class)
  .consistentWith(QueryScanConsistency.REQUEST_PLUS)
  .all();
----
====