[[spring-data-couchbase-reference-documentation]]
= Spring Data Couchbase
:revnumber: {version}
:revdate: {localdate}
:feature-scroll: true

_Spring Data Couchbase provides repository support for the Couchbase database.
It eases development of applications with a consistent programming model that need to access Couchbase data sources._

[horizontal]
xref:couchbase.adoc[Couchbase] :: Couchbase support and connectivity
xref:repositories.adoc[Repositories] :: Couchbase Repositories
xref:commons/migrating.adoc[Migration] :: Migration Guides
https://github.com/spring-projects/spring-data-commons/wiki[Wiki] :: What's New, Upgrade Notes, Supported Versions, additional cross-version information.

Michael Nitschinger, Oliver Gierke, Simon Basle, Michael Reiche, Tigran Babloyan

(C) 2014-{copyright-year} The original author(s)

Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically.
